#!/bin/bash
go test -coverprofile testProfile.tmp ./src > /dev/null
grep -v "config" testProfile.tmp > testProfile
go tool cover -html=testProfile
go tool cover -func=testProfile | grep total
rm testProfile testProfile.tmp
