#!/bin/bash
go test -coverpkg=./... -coverprofile=testProfile.tmp ./... || exit 0
grep -v "config" testProfile.tmp > testProfile

if [ "$1" != "noshow" ]; then
    go tool cover -html=testProfile
fi

go tool cover -func=testProfile | grep total
rm testProfile testProfile.tmp
